### ISSUE TITLE
Unable to build from source (mssing pypi_packaging)

### ISSUE THREAD

**Issue by matejsp** [cloudevents/sdk-python#161]
## Expected Behavior
```
pip wheel https://files.pythonhosted.org/packages/27/02/53f52041f2bfdf08ebb0fccb48b29ac2ac1cceefb424c4508081cc1ad82e/cloudevents-1.2.0.tar.gz
```

## Actual Behavior
```
(asdf) ➜  ~ pip wheel https://files.pythonhosted.org/packages/27/02/53f52041f2bfdf08ebb0fccb48b29ac2ac1cceefb424c4508081cc1ad82e/cloudevents-1.2.0.tar.gz
Collecting https://files.pythonhosted.org/packages/27/02/53f52041f2bfdf08ebb0fccb48b29ac2ac1cceefb424c4508081cc1ad82e/cloudevents-1.2.0.tar.gz
  Downloading cloudevents-1.2.0.tar.gz (15 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "/Users/matej.spiller-muys/asdf/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/Users/matej.spiller-muys/asdf/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/matej.spiller-muys/asdf/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/l6/nmk965l50gv_90_c4xh5x0_4ctpk94/T/pip-build-env-nr2q5szm/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/private/var/folders/l6/nmk965l50gv_90_c4xh5x0_4ctpk94/T/pip-build-env-nr2q5szm/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/l6/nmk965l50gv_90_c4xh5x0_4ctpk94/T/pip-build-env-nr2q5szm/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 281, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/private/var/folders/l6/nmk965l50gv_90_c4xh5x0_4ctpk94/T/pip-build-env-nr2q5szm/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 14, in <module>
          from pypi_packaging import pypi_config
      ModuleNotFoundError: No module named 'pypi_packaging'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
WARNING: There was an error checking the latest version of pip.
```

**Comment by xSAVIKx** [comment]
This should be resolved with https://github.com/cloudevents/sdk-python/pull/151. Also, you still won't be able to build from older released versions.

**Comment by xSAVIKx** [comment]
@matejsp the new v1.3.0 is available and you can use the following line to build the wheel package from it:
```
pip wheel https://files.pythonhosted.org/packages/15/a7/1f55dd7fd3a4f0fdada93ed5aec8eb7403b2bddd17f8fdee7ac2dcd0c21e/cloudevents-1.3.0.tar.gz
```

As I mentioned, the previous versions still can't be built this way.
